#!/bin/bash

GITCC_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
. "$GITCC_DIR/lib/common"

main() {
    local REV=$(git rev-parse HEAD)
    store
    if [ "$(git rev-parse HEAD)" != "$REV" ]; then
        echo "Current state stored"
    fi
}

main "$@"
