#!/bin/bash
. boot

usage() {
    echo "Start new feature branch"
    echo ""
    echo "Usage:"
    echo "  git feature <feature-name>"
    echo ""
}

main() {
    if [ -z "$1" ]; then
        usage
        exit 1
    fi

    create_and_checkout_branch "$1" feature dev
}

main "$@"
