#!/bin/bash

GITCC_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
. "$GITCC_DIR/common"

main() {
    header
    ask_branches
    ask_branch_prefixes
}

header() {
    echo "Setup your current repository to use git-cc helpers"
    echo "Current repository: $(root_dir)"
    echo ""
}

ask() {
    local QUESTION="$1: "
    local DEFAULT="${2:-$3}"
    local ANSWER=""

    if [ -n "$DEFAULT" ]; then
        QUESTION="$QUESTION[$DEFAULT] "
    fi

    while [ -z "$ANSWER" ]; do
        read -p "$QUESTION" ANSWER
        if [ -z "$ANSWER" ] && [ -n "$DEFAULT" ]; then
            ANSWER="$DEFAULT"
        fi
    done

    echo $ANSWER
}

ask_branch_prefix() {
    local TYPE="$1"
    local DEFAULT="$2"
    local CONFIG="$(branch_prefix "$TYPE")"
    local QUESTION="Choose prefix for $TYPE branches"
    local ANSWER=$(ask "$QUESTION" "$CONFIG" "$DEFAULT")
    branch_prefix "$TYPE" "$ANSWER"
}

ask_branch() {
    local TYPE="$1"
    local DEFAULT="$2"
    local CONFIG="$(branch_name "$TYPE")"
    local QUESTION="Choose prefix for $TYPE branches"
    local ANSWER=$(ask "$QUESTION" "$CONFIG" "$DEFAULT")
    branch_name "$TYPE" "$ANSWER"
}

ask_branch_prefixes() {
    ask_branch_prefix "feature" "feature-"
    ask_branch_prefix "hotfix"  "hotfix-"
    ask_branch_prefix "release" "release-"
}

ask_branches() {
    ask_branch "dev" "dev"
    ask_branch "master" "master"
}

main "$@"
