#!/bin/bash

GITCC_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
. "$GITCC_DIR/lib/common"

usage() {
    echo "Start new feature branch"
    echo ""
    echo "Usage:"
    echo "  git feature <feature-name>"
    echo ""
}

main() {
    if [ -z "$1" ]; then
        usage
        exit 1
    fi

    new_branch_and_checkout "$1" feature dev
}

main "$@"
