#!/bin/bash

GITCC_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
. "$GITCC_DIR/common"

usage() {
    echo "Start new hotfix branch"
    echo ""
    echo "Usage:"
    echo "  git hotfix <hotfix-name>"
    echo ""
}

main() {
    if [ -z "$1" ]; then
        usage
        exit 1
    fi

    local BRANCH="$(make_branch "$1" hotfix master)"
    git change-to "$BRANCH"
}

main "$@"
