#!/bin/bash
. boot

usage() {
    echo "Start new hotfix branch"
    echo ""
    echo "Usage:"
    echo "  git hotfix <hotfix-name>"
    echo ""
}

main() {
    if [ -z "$1" ]; then
        usage
        exit 1
    fi

    create_and_checkout_branch "$1" hotfix master
}

main "$@"
