#!/bin/bash

library_init() {
    local SCRIPT_DIR="$(script_dir "${BASH_SOURCE[0]}")"
    LIBRARY_DIR="${SCRIPT_DIR#$GITCC_DIR/}"
}

stderr() {
    echo "$@" >&2
}

info() {
    stderr "[*] $@"
}

warn() {
    stderr "[!] $@"
}

die() {
    warn "$@"
    exit 1
}

command_exists() {
    which "$@" >/dev/null 2>&1
}

function_exists() {
    type -t "$@" >/dev/null 2>&1
}

load() {
    . "$GITCC_DIR/$@"
}

load_library() {
    load "$LIBRARY_DIR/$1"
}

is_setup() {
    [ -n ${IS_SETUP:=0} ]
}

version_compare() {
    local VERSION="$1"
    local EXPECTED="$2"
    local LOWER=$(echo -e "$VERSION\n$EXPECTED" | sort -bgt. | head -1)
    [[ "$LOWER" = "$EXPECTED" ]]
}

ask() {
    local QUESTION="$1: "
    local DEFAULT="${2:-$3}"
    local ANSWER=""

    if [ -n "$DEFAULT" ]; then
        QUESTION="$QUESTION[$DEFAULT] "
    fi

    while [ -z "$ANSWER" ]; do
        read -p "$QUESTION" ANSWER
        if [ -z "$ANSWER" ] && [ -n "$DEFAULT" ]; then
            ANSWER="$DEFAULT"
        fi
    done

    echo $ANSWER
}

library_init
