#!/bin/bash

library_init() {
    GITHUB_TOKEN="github.token"

    if is_setup; then
        library_check
        library_setup
    fi
}

library_check() {
    if ! command_exists curl; then
        die "You must have cUrl installed to use the library GitHub"
    fi
}

library_setup() {
    if ! TOKEN=$(github_token); then
        load_library "github-auth"
        if ! TOKEN=$(github_authorize); then
            die "You must authorize git-cc for GitHub access"
        fi
        github_token "$TOKEN"
    fi
}

github_token() {
    config "$GITHUB_TOKEN" "$@"
}

github_request() {
    local METHOD="$1"
    local URL="https://api.github.com/${2/#\//}"
    local BODY="$3"; shift 3
    local CUSTOM_HEADERS=("$@")
    local OPTIONS=(-s -S -D "-" -X "$METHOD")
    local HEADERS=(-H "Accept: application/vnd.github.v3+full;json")
    local LOGIN=

    if [ -n "${CUSTOM_HEADERS[*]}" ]; then
        for HEADER in "${CUSTOM_HEADERS[@]}"; do
            if [ -n "$HEADER" ]; then
                HEADERS+=(-H "$HEADER")
            fi
        done
    fi

    local TOKEN="$(github_token)"
    if [ -n "$TOKEN" ]; then
        LOGIN="$TOKEN:x-oauth-basic"
    elif [ -n "$USER" ]; then
        LOGIN="$USER:$PASSWORD"
    fi

    if [ -n "$LOGIN" ]; then
        OPTIONS+=(-u "$LOGIN")
    fi

    if [ -n "$BODY" ]; then
        OPTIONS+=(-d "$BODY")
    fi

    curl "$URL" "${HEADERS[@]}" "${OPTIONS[@]}"
}

library_init
